name: Verify

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'

    - name: Run linters
      run: ./gradlew lint ktlintCheck --continue

    - name: Upload lib reports
      uses: actions/upload-artifact@v1.0.0
      if: ${{ always() }}
      with:
        name: lib-reports
        path: lib/build/reports

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'

    - name: Run JVM tests
      run: ./gradlew test

    - name: Upload lib reports
      uses: actions/upload-artifact@v1.0.0
      if: ${{ always() }}
      with:
        name: lib-reports
        path: lib/build/reports

  androidTest:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'
        cache: 'gradle'

    - name: Run Android tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: ./gradlew connectedAndroidTest

    - name: Upload lib reports
      uses: actions/upload-artifact@v1.0.0
      if: ${{ always() }}
      with:
        name: lib-reports
        path: lib/build/reports
